>Human_KIF11
MASQPNSSAKKKEEKGKNIQVVVRCRPFNLAERKASAHSIVECDPVRKEVSVRTGGLADK
SSRKTYTFDMVFGASTKQIDVYRSVVCPILDEVIMGYNCTIFAYGQTGTGKTFTMEGERS
PNEEYTWEEDPLAGIIPRTLHQIFEKLTDNGTEFSVKVSLLEIYNEELFDLLNPS-----
---SDVSERLQMFDDPRNKRGVIIKGLEEITVHNKDEVYQILEKGAAKRTTAATLMNAYS
SRSHSVFSVTIHMKETTIDGEELVKIGKLNLVDLAGSENIGRSGAVDKRAREAGNINQSL
LTLGRVITALVERTPHVPYRESKLTRILQDSLGGRTRTSIIATISPASLNLEETLSTLEY
AHRAKNILNKPEVNQKLTKKALIKEYTEEIERLKRDLAAAREKNGVYISEENFRVMSGKL
TVQEEQIVELIEKIGAVEEELNRVTELFMDNKNELDQCKSDLQNKTQELETTQKHLQETK
LQLVKEEYITSALESTEEKLHDAASKLLNTVEETTKDVSGLHSKLDRKKAVDQHNAEAQD
IFGKNLNSLFNNMEELIKDGSSKQKAMLEVHKTLFGNLLSSSVSALDTITTVALGSLTSI
PENVSTHVSQIFNMILKEQSLAAESKTVLQELINVLKTDLLSSLEMILSPTVVSILKINS
QLKHIFKTSLTVADKIEDQKKELDGFLSILCNNLHELQENTICSLVESQKQCGNLTEDLK
TIKQTHSQELCKLMNLWTERFCALEEKCENIQKPLSSVQENIQQKSKDIVNKMTFHSQKF
CADSDGFSQELRNFNQEGTKLVEESVKHSDKLNGNLEKISQETEQRCESLNTRTVYFSEQ
WVSSLNEREQELHNLLEVVSQCCEASSSDITEKSDGRKAAHEKQHNIFLDQMTIDEDKLI
AQNLELNETIKIGLTKLNCFLEQDLKLDIPTGTTPQRKSYLYPSTLVRTEPREHLLDQLK
RKQPELLMMLNCSENNKEETIPDVDVEEAVLGQYTEEPLSQEPSVDAGVDCSSIGGVPFF
QHKKSHGKDKENRGINTLERSKVEETTEHLVTKSRLPLRAQINLFF
>Satsuma
------------------------------------------------------------
------------------------------------------------------------
----------PEAGVIPRAVQQIFDTLESQNAEYSVKVTFLELYNEEITDLLAPDEISRA
AVEDKQKKQLPLMED--GKGGVLVRGLEEEIVTSASEIFTLLERGSAKRRTAETLLNKQS
SRSHSLFSITIHIKEATPEGEELIKCGKLNLVDLAGSENISRSGAREGRAREAGEINKSL
LTLGRVINALVEHLGHIPYRDSKLTRLLRDSLGGRTKTCIIATVSPAVHCLEETLSTLDY
AHRAKNIKNKPEVNQKMMKSTLIKDLYGEIDRLKAEVYAAREKNGVYIPKERY-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
>Valencia
------------------------------------------------------------
------------------------------------------------------------
----------PEAGVIPRAVQQIFDTLESQNAEYSVKVTFLELYNEEITDLLAPDEISRA
AVEDKQKKQLPLMED--GKGGVLVRGLEEEIVTSASEIFTLLERGSAKRRTAETLLNKQS
SRSHSLFSITIHIKEATPEGEELIKCGKLNLVDLAGSENISRSGAREGRAREAGEINKSL
LTLGRVINALVEHLGHIPYRDSKLTRLLRDSLGGRTKTCIIATVSPAVHCLEETLSTLDY
AHRAKNIKNKPEVNQKMMKSTLIKDLYGEIDRLKAEVYAAREKNGVYIPKERY-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
>field
------------------------------------------------------------
------------------------------------------------------------
----------PEAGVIPRTVKQIFDTLESQNAEYSVKVTFLELYNEEITDLLAPEEITKV
ALEDKQKKQLPLMED--GKGGVLVRGLEEEIVTSASEIFSLLERGSAKRRTAETLLNKQS
SRSHSLFSITIHIKEATPEGEELIKCGKLNLVDLAGSENISRSGAREGRAREAGEINKSL
LTLGRVINALVEHLGHIPYRDSKLTRLLRDSLGGRTKTCIIATVSPAVHCLEETLSTLDY
AHRAKNIKNKPEVNQKMMKSTLIKDLYGEIDRLKAEVYAAREKNGVYIPKERY-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
>Manihot
------------------------------------------------------------
------------------------------------------------------------
----------PEAGVIPRAVKQIFDTLESQNAEYSVKVTFLELYNEEITDLLAPEEISKV
ALEDKQKKQLPLMED--GKGGVLVRGLEEEIVTSASEIFTLLERGSAKRRTAETLLNKQS
SRSHSLFSITIHIKEATPEGEELIKCGKLNLVDLAGSENISRSGAREGRAREAGEINKSL
LTLGRVINALVEHLGHVPYRDSKLTRLLRDSLGGRTKTCIIATVSPAVHCLEETLSTLDY
AHRAKNIKNKPEVNQKMMKSTLIKDLYGEIERLKAEVYAAREKNGVYIPKERY-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
>CTRSC1NG
------------------------------------------------------------
------------------------------------------------------------
----------PEAGVIPRAVKQIFDTLESQNAEYSVKVTFLELYNEEITDLLAPEEISKV
ASEDKQKKQLLLMED--GKGGVLVRGLEEEIVTSASEIFTLLERGSAKRRTAETLLNKQS
SRSHSLFSITIHIKEATPEGEELIKCGKLNLVDLAGSENISRSGAREGRAREAGEINKSL
LTLGRVISALVEHLGHIPYRDSKLTRLLRDSLGGRTKTCIIATVSPAVHCLEETLSTLDY
AHRAKNIKNKPEVNQKMMKSTLIKDLYGEIDRLKAEVYAAREKNGVYIPKERY-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
>Morus
------------------------------------------------------------
------------------------------------------------------------
----------PEAGVIPRAVKQIFDTLESQNAEYSVKVTFLELYNEEITDLLAPEEISRV
ASEEKQKKQLPLMED--GKGGVLVRGLEEEIVTSASEIFTLLERGSAKRRTAETLLNKQS
SRSHSLFSITIHIKEATPEGEELIKCGKLNLVDLAGSENISRSGAREGRAREAGEINKSL
LTLGRVINALVEHLGHIPYRDSKLTRLLRDSLGGRTKTCIIATVSPAVHCLEETLSTLDY
AHRAKNIKNKPEVNQKMMKSTLIKDLYGEIDRLKAEVYAAREKVGVYIPKERY-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
