>Human_KIF11|NP_004514.2|kinesin-
MASQPNSSAKKKEEKGKNIQVVVRCRPFNLAERKASAHSIVECDPVRKEVSVRTGGLADK
SSRKTYTFDMVFGASTKQIDVYRSVVCPILDEVIMGYNCTIFAYGQTGTGKTFTMEGERS
PNEEYTWEEDPLAGIIPRTLHQIFEKLTDNGTEFSVKVSLLEIYNEELFDLLNPS-----
---SDVSERLQMFDDPRNKRGVIIKGLEEITVHNKDEVYQILEKGAAKRTTAATLMNAYS
SRSHSVFSVTIHMKETTIDGEELVKIGKLNLVDLAGSENIGRSGAVDKRAREAGNINQSL
LTLGRVITALVERTPHVPYRESKLTRILQDSLGGRTRTSIIATISPASLNLEETLSTLEY
AHRAKNILNKPEVNQKLTKKALIKEYTEEIERLKRDLAAAREKNGVYISEENFRVMSGKL
TVQEEQIVELIEKIGAVEEELNRVTELFMDNKNELDQCKSDLQNKTQELETTQKHLQETK
LQLVKEEYITSALESTEEKLHDAASKLLNTVEETTKDVSGLHSKLDRKKAVDQHNAEAQD
IFGKNLNSLFNNMEELIKDGSSKQKAMLEVHKTLFGNLLSSSVSALDTITTVALGSLTSI
PENVSTHVSQIFNMILKEQSLAAESKTVLQELINVLKTDLLSSLEMILSPTVVSILKINS
QLKHIFKTSLTVADKIEDQKKELDGFLSILCNNLHELQENTICSLVESQKQCGNLTEDLK
TIKQTHSQELCKLMNLWTERFCALEEKCENIQKPLSSVQENIQQKSKDIVNKMTFHSQKF
CADSDGFSQELRNFNQEGTKLVEESVKHSDKLNGNLEKISQETEQRCESLNTRTVYFSEQ
WVSSLNEREQELHNLLEVVSQCCEASSSDITEKSDGRKAAHEKQHNIFLDQMTIDEDKLI
AQNLELNETIKIGLTKLNCFLEQDLKLDIPTGTTPQRKSYLYPSTLVRTEPREHLLDQLK
RKQPELLMMLNCSENNKEETIPDVDVEEAVLGQYTEEPLSQEPSVDAGVDCSSIGGVPFF
QHKKSHGKDKENRGINTLERSKVEETTEHLVTKSRLPLRAQINL
>manioc(sequence
------------------------------------------------------------
------------------------------------------------------------
----------PEAGVIPRAVKQIFDTLESQNAEYSVKVTFLELYNEEITDLLAPEEISKV
ALEDKQKKQLPLMED--GKGGVLVRGLEEEIVTSASEIFTLLERGSAKRRTAETLLNKQS
SRSHSLFSITIHIKEATPEGEELIKCGKLNLVDLAGSENISRSGAREGRAREAGEINKSL
LTLGRVINALVEHLGHVPYRDSKLTRLLRDSLGGRTKTCIIATVSPAVHCLEETLSTLDY
AHRAKNIKNKPEVNQKMMKSTLIKDLYGEIERLKAEVYAAREKNGVYIPKERY-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>field
------------------------------------------------------------
------------------------------------------------------------
----------PEAGVIPRTVKQIFDTLESQNAEYSVKVTFLELYNEEITDLLAPEEITKV
ALEDKQKKQLPLMED--GKGGVLVRGLEEEIVTSASEIFSLLERGSAKRRTAETLLNKQS
SRSHSLFSITIHIKEATPEGEELIKCGKLNLVDLAGSENISRSGAREGRAREAGEINKSL
LTLGRVINALVEHLGHIPYRDSKLTRLLRDSLGGRTKTCIIATVSPAVHCLEETLSTLDY
AHRAKNIKNKPEVNQKMMKSTLIKDLYGEIDRLKAEVYAAREKNGVYIPKERY-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Satsuma
------------------------------------------------------------
------------------------------------------------------------
----------PEAGVIPRAVQQIFDTLESQNAEYSVKVTFLELYNEEITDLLAPDEISRA
AVEDKQKKQLPLMED--GKGGVLVRGLEEEIVTSASEIFTLLERGSAKRRTAETLLNKQS
SRSHSLFSITIHIKEATPEGEELIKCGKLNLVDLAGSENISRSGAREGRAREAGEINKSL
LTLGRVINALVEHLGHIPYRDSKLTRLLRDSLGGRTKTCIIATVSPAVHCLEETLSTLDY
AHRAKNIKNKPEVNQKMMKSTLIKDLYGEIDRLKAEVYAAREKNGVYIPKERY-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Valencia
------------------------------------------------------------
------------------------------------------------------------
----------PEAGVIPRAVQQIFDTLESQNAEYSVKVTFLELYNEEITDLLAPDEISRA
AVEDKQKKQLPLMED--GKGGVLVRGLEEEIVTSASEIFTLLERGSAKRRTAETLLNKQS
SRSHSLFSITIHIKEATPEGEELIKCGKLNLVDLAGSENISRSGAREGRAREAGEINKSL
LTLGRVINALVEHLGHIPYRDSKLTRLLRDSLGGRTKTCIIATVSPAVHCLEETLSTLDY
AHRAKNIKNKPEVNQKMMKSTLIKDLYGEIDRLKAEVYAAREKNGVYIPKERY-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Morus
------------------------------------------------------------
------------------------------------------------------------
----------PEAGVIPRAVKQIFDTLESQNAEYSVKVTFLELYNEEITDLLAPEEISRV
ASEEKQKKQLPLMED--GKGGVLVRGLEEEIVTSASEIFTLLERGSAKRRTAETLLNKQS
SRSHSLFSITIHIKEATPEGEELIKCGKLNLVDLAGSENISRSGAREGRAREAGEINKSL
LTLGRVINALVEHLGHIPYRDSKLTRLLRDSLGGRTKTCIIATVSPAVHCLEETLSTLDY
AHRAKNIKNKPEVNQKMMKSTLIKDLYGEIDRLKAEVYAAREKVGVYIPKERY-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
